name: dart_services
publish_to: none

environment:
  # Keep min SDK aligned with .travis.yml and FROM line of Dockerfile
  sdk: '>=2.4.1 <3.0.0'

dependencies:
  _discoveryapis_commons: ^0.1.8
  analyzer: ^0.36.0
  analysis_server_lib: ^0.1.4
  appengine: ^0.10.0
  args: ^1.5.2
  bazel_worker: ^0.1.21
  crypto: ^2.0.0
  dartis: ^0.3.0
  http: ^0.12.0
  logging: ^0.11.0
  path: ^1.6.2
  shelf: ^0.7.0
  rpc: ^0.6.1
  uuid: ^2.0.0
  yaml: ^2.1.15
  quiver: ">=0.25.0"
  react: ^4.4.2
  over_react: ^1.30.2
  web_skin:
    hosted:
      name: web_skin
      url: https://pub.workiva.org
    version: ^1.53.1
  web_skin_dart:
    hosted:
      name: web_skin_dart
      url: https://pub.workiva.org
    version: ^2.31.0

dev_dependencies:
  discoveryapis_generator: ^0.9.11
  async: ^2.2.0
  codemirror: ^0.5.6
  coverage: ^0.13.0
  grinder: ^0.8.0
  pedantic: ^1.8.0
  synchronized: ^2.1.0
  test: ^1.6.4
  tuneup: ^0.3.6

dependency_overrides:
  react:
    git:
      url: git@github.com:cleandart/react-dart.git
      ref: 5.1.0-wip
  over_react:
    path: ../over_react
  web_skin_dart:
    git:
      url: git@github.com:Workiva/web_skin_dart.git
      ref: react-16-wip

executables:
  services: null
